In [1]:
import numpy as np 

### Crear un arreglo de ceros de longitud 12

In [9]:
arr = np.zeros(12)
print(arr.size)

12


### Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [13]:
arr2 = np.zeros(10)
arr2[5] = 10
print(arr2)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


### Crear un arreglo que tenga los números del 10 al 49

In [20]:
arr3 = np.arange(start = 10, stop = 49, step = 1)
print(arr3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [23]:
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [44]:
randArray = np.random.randint(100, size=100)
media = np.mean(randArray)
varianza = np.var(randArray)
print("randArray = ", randArray)
print("media = ", media)
print("varianza = ", varianza)

randArray =  [49 28 11  0 84 69 12 80 74 60 78 59 32 89 77 28  1 18 11 20 93 55 44  3
  7 90 72 79 77 50 35 56 33 49 97 91  0  8 32 89  3 70  7 76 10 53 40 19
  7 10  7 14 40 63 27 72 17 26 53 27 99 50 64 83 95  2 22 66 48  5 13 52
 41 86  7 98  7 73 47 11 35 53 84 30 86 23 76 18 59 38 37 79 68 10 10 72
 97 30 70 47]
media =  45.72
varianza =  907.0616


### Calcular la media de un arreglo usando np.sum

In [45]:
x = randArray
mediasum = np.sum(x)/x.size
print("media = ", mediasum)

media =  45.72


### Calcular la varianza de un arreglo usando np.sum y np.mean