# Introducción a numpy

#### Librería optimizada para realizar cálculos numéricos con vectores y matrices

In [3]:
import numpy as np

#### Podemos definir arrays a partir de listas

In [ ]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print(type(arr))

In [ ]:
lista = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
arr = np.array(lista)

#### Los arrays y las listas se comportan diferente frente operaciones matematicas con números

In [ ]:
#print(lista + 2) # da error
print(arr + 2) # suma 2 a cada elemento

In [ ]:
print(lista * 2) # duplica la lista
print(arr * 2) # multiplica por dos cada elemento

#### Los arrays y las listas se comportan diferente frente a operaciones con otros arrays/listas

In [ ]:
lista1 = [1, 2, 3, 4, 5]
lista2 = [5, 4, 3, 2, 1]

arr1 = np.array(lista1)
arr2 = np.array(lista2)

In [ ]:
print('suma de listas =', lista1 + lista2) # concatena (une) las dos listas
print('suma de arreglos =', arr1 + arr2) # suma los elementos de cada arreglo

In [ ]:
#print(lista1 * lista2) # da error
print('multiplicación de arreglos =', arr1 * arr2) # multiplica los elementos de cada arreglo

In [ ]:
print('resta =', arr1 - arr2)
print('division =', arr1 / arr2)
print('exponenciacion =', arr1 ** arr2)
print('combinacion de operaciones =', (arr1 - arr2)/(arr1 + arr2) * arr1)

#### Para arrays1d la indexación funciona igual que para las listas

In [ ]:
lista = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
arr = np.array(lista)

In [ ]:
print(lista[0], arr[0]) # devuelve el 1er elemento
print(lista[4], arr[4]) # devuelve el 5to elemento
print(lista[:3], arr[:3])
print(lista[1:7], arr[1:7])
print(lista[3:], arr[3:])
print(lista[-1], arr[-1])
print(lista[:-1], arr[:-1])
print(lista[::-1], arr[::-1])

In [ ]:
lista[2:5] = [22, 23, 24]
arr[2:5] = [22, 23, 24]
print(lista)
print(arr)

# Arreglos multidimensionales

#### Las listas son cadenas unidimensionales de elementos. Los arreglos pueden ser multidimensionales

In [ ]:
lista = [[0, 1, 3], [3, 4, 5]]
array_2d = np.array(lista)
array_2d

In [ ]:
print(array_2d.ndim)

In [ ]:
print(array_2d.shape)

In [ ]:
print(array_2d.size)

#### En scikit-learn array_2d=(samples, features)

#### **Desafío:** armar un array 3d a partir de una lista de listas <br>
#### Queremos que *array3d.ndim==3* devuelva *True*

In [ ]:
lista = [[0, 1], [2, 3]]
lista = [lista, lista]
arr3d = np.array(lista)
print(arr3d.shape)

In [ ]:
print(arr2d[0, 1])
#print(arr3d[0, 1, 1])
#print(arr3d[0, 1, :])
#print(arr3d[0, 1, :2])
#print(arr3d[0, :, :1])
#print(arr3d[0, 1, -1])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print(arr.reshape(2, 3))

# Creación de arreglos

In [ ]:
# print(np.zeros(10))
# print(np.zeros((3, 2)))
# print(np.zeros((10, 5)))
print(np.zeros((2, 2, 2)))

In [ ]:
# np.ones(10)
# np.ones((3, 2))
# np.ones((10, 5))
# np.ones((2, 2, 2))

In [ ]:
print(np.random.rand(10), '\n')
print(np.random.rand(3, 2), '\n')
print(np.random.rand(10, 5), '\n')
print(np.random.rand(2, 2, 2))

In [ ]:
print(np.random.randn(10), '\n')
print(np.random.randn(3, 2), '\n')
print(np.random.randn(10, 5), '\n')
print(np.random.randn(2, 2, 2))

In [ ]:
np.random.randint(5)

In [ ]:
print(np.random.randint(10, size=10), '\n')
print(np.random.randint(10, size=(3, 3)), '\n')

In [ ]:
# np.arange(10)
# np.arange(0, 10, 1) # start, stop, step
np.arange(2, 16, 2)
np.arange(0, 10, .1)

In [ ]:
np.linspace(0, 10, 11) # start, stop, length
np.linspace(0, 10, 101)

In [ ]:
np.append(np.zeros(5), 1.)
# np.append(np.zeros(5), np.ones(5))
# np.concatenate((np.zeros(5), np.ones(5), np.arange(5)))
# np.stack((np.zeros(5), np.ones(5)), axis=0)
# np.stack((np.zeros(5), np.ones(5)), axis=1)

In [ ]:
# print(np.nan, np.inf)
# print(np.exp(1000))
np.zeros((10, 10)) * np.nan

**Desafío:** crear un array 1d de longitud 10 que tenga el número 5 en todas sus posiciones <br>
**Desafío:** crear un array 1d que tenga todos los números del 1 al 40 pero con todos los pares primero y los impares después <br>
**Desafío usando google:** crear un array 1d de longitud 20 que tenga los números del 1 al 20 desordenados <br>

In [ ]:
#np.ones(10) * 5
np.append(np.arange(2, 42, 2), np.arange(1, 40, 2))

# Funciones

## Promedio o media
$$
X = (x_1, x_2,...,x_N)
$$

$$
\bar{x}=\frac{1}{N}\sum_{n=1}^{N} x_n
$$

#### Valor esperado

In [4]:
X = np.ones(7) * 4
print(X)
print(np.mean(X))

[4. 4. 4. 4. 4. 4. 4.]
4.0


In [5]:
X = np.arange(2, 7)
np.random.shuffle(X)
print(X)
print(np.mean(X))

[5 6 3 4 2]
4.0


In [ ]:
X = np.arange(1, 8)
print(X)
print(np.mean(X))

In [ ]:
X = np.arange(1, 10).reshape(3, 3)
print(X, '\n')
print(np.mean(X, 0), '\n') # o np.mean(X, axis=0)
print(np.mean(X, 1)) # o np.mean(X, axis=1)

In [ ]:
np.mean?

## Varianza
$$
\sigma_x=\frac{1}{N}\sum_{n=1}^{N} (x_n - \bar{x})^2
$$

#### Mide la dispersión de los valores alrededor de la media

In [ ]:
X = np.ones(7) * 4
print(X)
print(np.var(X))

In [ ]:
X = np.arange(2, 7)
print(X)
print(np.var(X))

In [ ]:
X = np.arange(1, 8)
print(X)
print(np.var(X))

In [ ]:
X = np.arange(1, 10).reshape(3, 3)
print(X, '\n')
print(np.var(X, 0), '\n') # o np.var(X, axis=0)
print(np.var(X, 1)) # o np.var(X, axis=1)

Otras

In [6]:
X = np.arange(-3, 4)
print(X)
print(np.min(X))
print(np.max(X))
print(np.sum(X))
# también funcionan con axis

[-3 -2 -1  0  1  2  3]
-3
3
0


In [ ]:
X = np.arange(-3, 4)
print(np.abs(X))
print(np.sign(X))

In [ ]:
X = np.arange(1, 8)
np.random.shuffle(X)
print(X)
arg_min = np.argmin(X)
arg_max = np.argmax(X)
print(arg_min, X[arg_min])
print(arg_max, X[arg_max])

In [ ]:
X = np.arange(1, 8) + 0.7
print(X)
print(np.round(X, 0))

# Máscaras booleanas

In [ ]:
arr = np.array([0., 1.])
mask = np.array([True, False])
print(mask)
print(mask.dtype)
print(arr)
print(arr.dtype)

In [ ]:
arr = np.arange(10)
print(arr)
print(arr > 3)
print(~(arr > 3))
print((arr > 3) & (arr < 8))
print((arr < 3) | (arr > 8))

#### Puedo filtrar datos

In [ ]:
arr = np.array([5., 10.])
mask = np.array([True, False])
print(arr[mask])

In [ ]:
arr = np.arange(10)
mask = (arr > 3) & (arr < 8)
print(arr[mask])

#### Devuelvo siempre un array 1d

In [ ]:
arr = np.arange(10).reshape(2, 5)
mask = (arr > 3) & (arr < 8)
print(arr)
print(arr[mask])

#### Puedo usar *np.zeros* y *np.ones* para crear arrays de False y True

In [ ]:
np.zeros(10, dtype=bool)
# np.ones(10, dtype=bool)

#### np.any y np.all

In [ ]:
mask = np.zeros(10, dtype=bool)
print(mask, '  any=', np.any(mask))
mask[5] = True
print(mask, '  any=', np.any(mask))

In [ ]:
mask = np.ones(10, dtype=bool)
print(mask, '  all=', np.all(mask))
mask[5] = False
print(mask, '  all=', np.all(mask))

In [ ]:
mask = np.array(np.random.randint(2, size=(3, 3)), dtype=bool)
print(mask, '\n')
print(np.all(mask, 0), '\n')
print(np.all(mask, 1))

In [ ]:
mask = np.array(np.random.randint(2, size=10), dtype=bool)
print(mask, '\n')
print(np.where(mask), '\n')

In [ ]:
mask = np.array(np.random.randint(2, size=(3, 3)), dtype=bool)
print(mask, '\n')
print(np.where(mask), '\n')

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn y llenar con ceros todas las posiciones menores a 0 usando una máscara
9. Crear el array np.arange(10) e insertar el número 0 en todos los valores pares usando una máscara
10. Crear un arreglo de números aleatorios de longitud 10. Hallar el valor mínimo y reemplazarlo por 0