# if, for statements

## If statement

In [1]:
if True:
  print('Corrí esta linea')
  
if False:
  print('Corro esta linea?')

Corrí esta linea


#### Ya vimos que escribir comparaciones devuelve su condicion de verdad

In [2]:
print('Es 3<5?', 3<5)
print('Es 3>5?', 3>5)

Es 3<5? True
Es 3>5? False


#### Entonces las podemos evaluar con el if statement

In [3]:
if 3 < 5:
  print('3 es menor que 5')
else:
  print('3 no es menor que 5')
  
if 3 > 5:
  print('3 es mayor que 5')
else:
  print('3 no es mayor que 5')
  

3 es menor que 5
3 no es mayor que 5


In [4]:
a = 3
b = 5
if a>b:
    print("%i es mayor que %i" % (a, b))
elif a<b:
    print("%i es menor que %i" % (a, b))
else:
    print("%i no es ni menor ni mayor que %i, debe ser igual!" % (a, b))
    print(a==b)
    

3 es menor que 5


## for loops
#### for es otro statement de python, este nos permite repetir la mismas lineas de código con distintos elementos

In [5]:
for i in range(5):
  print(i)

0
1
2
3
4


#### utiliza diferentes tipos variables llamados "iterables"

In [6]:
iterable1 = [0, 1, 2]
iterable2 = range(3)
iterable3 = {0:2, 1:3, 2:5} 
iterable4 = "los 'strings' tambien son iterables!"
for elemento in iterable1:
  print(elemento)
print('\n')
for elemento in iterable2:
  print(elemento)
print('\n')
for elemento in iterable3:
  print(elemento)
print('\n')
for elemento in iterable4:
  print(elemento)
  
print('Cualquier numero es un ejemplo de objeto no iterable:')
for elemento in 4:
      print(elemento)

0
1
2


0
1
2


0
1
2


l
o
s
 
'
s
t
r
i
n
g
s
'
 
t
a
m
b
i
e
n
 
s
o
n
 
i
t
e
r
a
b
l
e
s
!
Cualquier numero es un ejemplo de objeto no iterable:


TypeError: 'int' object is not iterable

In [7]:
for j in range(11):
  if j % 2 == 0:
    print("%i es divisible por 2" % j)

0 es divisible por 2
2 es divisible por 2
4 es divisible por 2
6 es divisible por 2
8 es divisible por 2
10 es divisible por 2


In [8]:
lista = [3, 7, 5]
b = 5
for a in lista:
    if a>b:
        print("%i es mayor que %i" % (a, b))
    elif a<b:
        print("%i es menor que %i" % (a, b))
    else:
        print("%i no es ni menor ni mayor que %i, debe ser igual!" % (a, b))
        print(a==b)

3 es menor que 5
7 es mayor que 5
5 no es ni menor ni mayor que 5, debe ser igual!
True


# List comprehension (comprension de listas)
####  Ahora que vimos cómo funcionan las listas, algunos statements  y loops, podemos poner todo una linea para generar listas

In [9]:
[x for x in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
{x: x+1 for x in range(10)}

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10}

In [10]:
[x for x in range(10) if x % 2 == 0]

[0, 2, 4, 6, 8]

#### Finalmente, podemos convertir iterables que no son tipo "lista" en listas con la funcion list()

In [14]:
diccionario = {1: 2, 3: 4}
print(type(diccionario))
lista = list(diccionario)
print(lista)
print(type(lista))

<class 'dict'>
[1, 3]
<class 'list'>


In [16]:
def espalindromo(palabra):
    if palabra.lower() == palabra.lower()[::-1]:
        return True
    else: 
        return False

In [18]:
espalindromo('banana')

False

# Modulo Numpy
#### veamos que funciones tiene numpy que podemos aplicar a listas

In [2]:
import numpy as np

In [3]:
np.random.random(10)

array([0.84044073, 0.60411776, 0.28964165, 0.41696918, 0.92066955,
       0.63217393, 0.4778487 , 0.85772108, 0.03171182, 0.6260986 ])

#### numpy se maneja con con arreglos (arrays) pero tambien podemos usarlo para realizar operaciones sobre listas.
#### Convertimos un arreglo de numpy (nos vamos a meter con ellos la semana que viene)

In [7]:
lista_de_randoms = list(np.random.random(10))
print(lista_de_randoms)
print(type(lista_de_randoms))

[0.8137352472861805, 0.28142066212894146, 0.8816922612531226, 0.3337041860011061, 0.6098332464967896, 0.2608312055782479, 0.9247167384844052, 0.18901676771299258, 0.5319817866960957, 0.2738389150239118]
<class 'list'>


In [8]:
type(np.random.random(10))

numpy.ndarray

In [9]:
np.mean(lista_de_randoms)

0.5100771016661794

In [10]:
np.min(lista_de_randoms)

0.18901676771299258

In [11]:
np.max(lista_de_randoms)

0.9247167384844052

In [12]:
lista_de_randoms[np.argmax(lista_de_randoms)]

0.9247167384844052

In [13]:
np.argmin(lista_de_randoms)

7

In [14]:
np.std(lista_de_randoms)

0.2677809060817375

In [15]:
np.var(lista_de_randoms)

0.07170661366195631

In [16]:
squared_std = np.power(np.std(lista_de_randoms), 2)
print(squared_std)
print(np.std(lista_de_randoms)**2)

0.07170661366195631
0.07170661366195631


In [18]:
print(np.power(lista_de_randoms, 2))
np.array(lista_de_randoms) ** 2

[0.66216505 0.07919759 0.77738124 0.11135848 0.37189659 0.06803292
 0.85510105 0.03572734 0.28300462 0.07498775]


array([0.66216505, 0.07919759, 0.77738124, 0.11135848, 0.37189659,
       0.06803292, 0.85510105, 0.03572734, 0.28300462, 0.07498775])

In [19]:
print(sum(lista_de_randoms))
print(np.sum(lista_de_randoms))

5.100771016661794
5.100771016661794


In [27]:
np.diff(lista_de_randoms)

array([ 0.49379647,  0.10605941,  0.114734  , -0.19004142, -0.39770339,
        0.37999969, -0.04252859, -0.37682214,  0.34491186])

In [21]:
np.diff([0, 3, 5])

array([3, 2])

### y tambien tiene funciones matematicas y constantes

In [29]:
np.exp(0)

1.0

In [30]:
np.cos(0)

1.0

In [34]:
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


In [32]:
np.sin(np.pi)

1.2246467991473532e-16

In [33]:
np.cos(np.pi)

-1.0